---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Install httpd package
    yum: name=httpd state=latest
  - name: Copy index.html
    copy: src=files/index.html dest=/var/www/html/index.html
    notify:
    - restart apache
  - name: start and Enable httpd service
    service: name=httpd state=restarted enabled=yes
  handlers:
  - name: restart apache
    service: name=httpd state=restarted
